# Service Account for o2ims
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.o2ims.serviceaccountname }}
  namespace: orano2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.o2ims.serviceaccountname }}
subjects:
- kind: ServiceAccount
  namespace: orano2
  name: {{ .Values.o2ims.serviceaccountname }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
